#!/bin/bash
# Заходим в нужную директорию с файлами из второй задачи
cd /path/to/directory
# Объединяем все файлы в один
cat *.fasta > output.fasta
#Форматируем последовательности по 60 символов на одну строку
fold -w 60 output.fasta > final.fasta
